# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06server\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x32\xe3\x01\n\x06Server\x12)\n\x03\x41\x64\x64\x12\x0e.server.addMsg\x1a\x10.server.addReply\"\x00\x12\x35\n\x08RawImage\x12\x13.server.rawImageMsg\x1a\x12.server.imageReply\"\x00\x12>\n\nDotProduct\x12\x15.server.dotProductMsg\x1a\x17.server.dotProductReply\"\x00\x12\x37\n\tJsonImage\x12\x14.server.jsonImageMsg\x1a\x12.server.imageReply\"\x00\x42/\n\x17io.grpc.examples.serverB\x0bServerProtoP\x01\xa2\x02\x04srvrb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027io.grpc.examples.serverB\013ServerProtoP\001\242\002\004srvr'
  _globals['_ADDMSG']._serialized_start=24
  _globals['_ADDMSG']._serialized_end=54
  _globals['_RAWIMAGEMSG']._serialized_start=56
  _globals['_RAWIMAGEMSG']._serialized_end=82
  _globals['_DOTPRODUCTMSG']._serialized_start=84
  _globals['_DOTPRODUCTMSG']._serialized_end=121
  _globals['_JSONIMAGEMSG']._serialized_start=123
  _globals['_JSONIMAGEMSG']._serialized_end=150
  _globals['_ADDREPLY']._serialized_start=152
  _globals['_ADDREPLY']._serialized_end=175
  _globals['_DOTPRODUCTREPLY']._serialized_start=177
  _globals['_DOTPRODUCTREPLY']._serialized_end=214
  _globals['_IMAGEREPLY']._serialized_start=216
  _globals['_IMAGEREPLY']._serialized_end=259
  _globals['_SERVER']._serialized_start=262
  _globals['_SERVER']._serialized_end=489
# @@protoc_insertion_point(module_scope)
